# Generated by Django 5.0.6 on 2024-07-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myprofile", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="username",
            new_name="name",
        ),
    ]
