# Generated by Django 5.0.6 on 2024-07-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myprofile", "0003_rename_username_profile_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="name",
            new_name="username",
        ),
    ]
