# Generated by Django 5.0.6 on 2024-07-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrating',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chatrating',
            name='rater',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatRating',
        ),
    ]
