# Generated by Django 5.0.6 on 2024-07-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_chat_chat_question_chat_answer_chatrating_evaluation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrating',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chatrating',
            name='rater',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatRating',
        ),
    ]
