# Generated by Django 5.0.6 on 2024-07-05 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_alter_chat_question_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_question',
            name='asker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to='question.mentorprofile'),
        ),
    ]
