# Generated by Django 5.0.6 on 2024-07-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_evaluation_mentorprofile_alter_chat_question_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_question',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
